language: php

php:
- 7.0
- 7.1

env:
- NO_INTERACTION=1 REPORT_EXIT_STATUS=1

compiler:
- gcc

install:
- sudo apt-get update -qq
- sudo apt-get install -qq automake pkg-config build-essential libtool automake autoconf m4 gnulib

script:
- ./travis/test
